#!/bin/bash
rm -f cache
echo "création d'un fichier déja  trier"
for fichier in *;do file $fichier|grep 'JPEG\|PNG'|sed "s/: /./"|cut -d " " -f 1|tee -a  cache;done
nbfichier=$(wc cache -l|cut -d " " -f 1)
 
counter=0
echo "initialisation de la boucle"
time while read ligne;
do	
	((counter+=1))
	movefile=$(cp -v $(echo $ligne|cut -d "." -f 1) $(echo $ligne|perl -ne 'print lc') 2> /dev/null)
	echo $counter"/"$nbfichier $movefile ; done < cache
rm cache
echo "fin du programe"
